// Generated by https://quicktype.io

export interface Client {
  id:        number;
  names:     string;
  surnames:  string;
  email:     string;
  phone:     string;
  address:   string;
  planId:    number;
  trainerId: number | null;
  userId:    number;
}
