// Generated by https://quicktype.io

export interface Plan {
  id:             number;
  name:           string;
  description:    string;
  durationInDays: number;
  price:          number;
  status:         boolean;
}
