// Generated by https://quicktype.io

export interface Trainer {
  id:       number;
  names:    string;
  surnames: string;
  email:    string;
  phone:    string;
  address:  string;
  userId:   number;
}
